{{- if not .Values.registration.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wazuh-agent.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wazuh-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  authd.pass: {{ .Values.registration.password | quote }}
{{- end }}
