apiVersion: v2
name: wazuh-agent
description: A Helm chart for deploying Wazuh agents on Kubernetes as a DaemonSet.
type: application
version: 4.14.2
appVersion: "4.14.2"
keywords:
  - wazuh
  - security
  - monitoring
  - siem
  - agent
home: https://wazuh.com
sources:
  - https://github.com/wazuh/wazuh
  - https://github.com/MaximeWewer/wazuh-agent-helm
maintainers:
  - name: Maxime Wewer
    url: https://github.com/MaximeWewer/
kubeVersion: ">=1.20.0-0"
